server:
  port: 8088
  servlet:
    jsp:
      init-parameters:        development: true    context-path: /joinChain

#spring
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pms?characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

    # 使用 druid 作为连接池  更多配置的说明可以参见 druid starter 中文文档 https://github.com/alibaba/druid/tree/master/druid-spring-boot-starter
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
     #配置初始化大小/最小/最大
     initialSize: 5
     minIdle: 5
     maxActive: 20
     #获取连接等待超时时间
     maxWait: 60000
     #间隔多久进行一次检测，检测需要关闭的空闲连接
     timeBetweenEvictionRunsMillis: 60000
     #一个连接在池中最小生存的时间
     minEvictableIdleTimeMillis: 300000
     validationQuery: SELECT 1 FROM DUAL
     testWhileIdle: true
     testOnBorrow: false
     testOnReturn: false
     poolPreparedStatements: true
     maxPoolPreparedStatementPerConnectionSize: 20
     filters: stat,wall,log4j
     connectionProperties: druid.stat.mergeSql=true;druid.stat.logSlowSql=true;druid.stat.slowSqlMillis=5000

  mvc:
    view:
     prefix: /WEB-INF/page/
     suffix: .jsp
     
mybatis: 
  mapperLocations: classpath:com/joinChain/medicalCare/mapper/xml/*.xml

mybatis-plus:
  # 如果是放在src/main/java目录下 classpath:/com/yourpackage/*/mapper/*Mapper.xml
  # 如果是放在resource目录 classpath:/mapper/*Mapper.xml
  mapper-locations: classpath:com/joinChain/medicalCare/mapper/xml/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.joinChain.medicalCare.*.entity
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 3
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 2
    #刷新mapper 调试神器
    refresh-mapper: true
    #自定义填充策略接口实现
    meta-object-handler: com.joinChain.medicalCare.common.mybatis.CommonMetaObjectHandler
  #configuration:    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #调试打印sql
    
#配置关闭swagger2接口
swagger2:
  enable: true
